### ISSUE TITLE
10-12kV high voltage source should be DC/which power source you used?

### ISSUE THREAD

**Issue by AbidHussain70** [bhclowers/OS-IMS#5]
What kind of power supply will work good for IMS?
Power supply source should be DC or can I use circuit made from flyback transformers (relatively cheap option). I noticed that circuit with flyback transformer add noise at higher voltage?

**Comment by bhclowers** [comment]
Flyback transformers and other switching supplies are exceedingly noisy.  I'm not saying they won't work but I have not seen anyone use them successfully. I would imagine that it would be possible to use a switching supply but a considerable amount of voltage conditioning would be needed.  Keep in mind that fluctuations in the tube voltage will induce noise on the detector and broaden peaks.  Additionally, voltage fluctuations that approach 1% at 10 kV are entirely unacceptable--this will cause the ions to shift constantly and introduces unecessary degress of experimental error (i.e. what is the voltage applied and experienced by the ions?).  

I do know that certain vendors have devised specific power supplies that use switching approaches but they are also investing heavily into an engineering team.  Provided you don't have the latter, I would recommend the [ultravolt series](https://www.advancedenergy.com/products/high-voltage-products/high-voltage-power-supplies/standard-size-dc-to-high-voltage-modules/a-series/). They are relatively low-cost, compact, and when factoring the amount of time you will spend designing and testing your own solution, this price is worth the money.  Just know that you need to pair this with an suitable HV capacitor and hook it to the tube (i.e. the resistor chain) in order to for the circuit to work correctly.  It doesn't like working without a load.  I don't know the exact underlying architecture but looking at the signal on a scope, they too use a switching supply under the hood--they just smooth it out to a decent degree.  

Good luck and wish I had a better answer for you.

**Comment by AbidHussain70** [comment]
I order[ EMCO DC–HV DC Converters](https://www.digikey.com/en/product-highlight/x/xp-power/dcdc-converters-emco)
and also I got one switching power supply (3kV-18kV) from Chinese vendor, Chinese one is under 100 dollars. Currently I have 100x oscilloscope probe and I can test maximum 5kV signal with my oscilloscope. 
I will order 1000x probe and I will attached the results here once I check the output fluctuation of the power supply.

**Comment by bhclowers** [comment]
Be mindful of the power supplies that are unregulated.

**Comment by AbidHussain70** [comment]
I checked the noise of HV, which I bought from Chinese Vendor, peak to peak noise is between 1-2%. 
With 6.4KV it gives almost 80-100V peak to peak noise.
![HV-ripple](https://user-images.githubusercontent.com/23444211/111110041-cdd7e980-8596-11eb-95fd-453d1ce7070a.jpg)

**Note: Oscilloscope probe is 1000x.**

**Comment by bhclowers** [comment]
As I mentioned, using an unregulated supply can pose a challenge.  It is also important that you check the ripple when the power supply is connected to a load (i.e. the IMS cell or some other resistive divider). Finally, you may consider using a HV capacitor to ground (but make sure it is large enough for the voltage) as this may reduce the ripple. 

![image](https://user-images.githubusercontent.com/385793/111112294-28346400-851d-11eb-946c-f757f83505e0.png)

**Comment by AbidHussain70** [comment]
I received HV capacitor today, I will put this capacitor in parallel and  I will test the output of the HV power source.
